services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    privileged: true
    env_file: .env
    volumes:
      - /mnt/home-assistant:/config
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  scrypted:
    container_name: scrypted
    image: ghcr.io/koush/scrypted
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer ${SCRYPTED_TOKEN}
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    volumes:
      - /mnt/scrypted:/server/volume
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"

  watchtower:
    container_name: scrypted-watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${SCRYPTED_TOKEN}
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --scope scrypted
    ports:
      - 10444:8080
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    env_file: .env
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./services/otel-collector/config.yaml:/etc/otelcol/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
